#!/bin/bash

# Seed Applications for AuthService
# This script creates default applications that can authenticate with the AuthService

BASE_URL="http://localhost:5067"

echo "🌱 Seeding Applications..."
echo ""

# You'll need to create an admin endpoint to register applications
# For now, we'll add them directly to the database

echo "To add applications, run these SQL commands in your PostgreSQL database:"
echo ""
echo "-- Email Service Application"
echo "INSERT INTO \"Applications\" (\"Id\", \"Name\", \"ClientId\", \"ClientSecret\", \"Description\", \"IsActive\", \"AllowedOrigins\", \"AllowedScopes\", \"CreatedAt\")"
echo "VALUES ("
echo "  gen_random_uuid(),"
echo "  'Email Service',"
echo "  'email-service-client',"
echo "  '\$2a\$11\$hashed_secret_here', -- You need to hash 'email-service-secret-123'"
echo "  'Main email marketing and campaign service',"
echo "  true,"
echo "  '{\"http://localhost:3000\", \"http://localhost:5173\", \"https://email.yourdomain.com\"}',"
echo "  '{\"email:send\", \"email:read\", \"campaigns:manage\"}',"
echo "  NOW()"
echo ");"
echo ""
echo "-- Dashboard Application"
echo "INSERT INTO \"Applications\" (\"Id\", \"Name\", \"ClientId\", \"ClientSecret\", \"Description\", \"IsActive\", \"AllowedOrigins\", \"AllowedScopes\", \"CreatedAt\")"
echo "VALUES ("
echo "  gen_random_uuid(),"
echo "  'Admin Dashboard',"
echo "  'admin-dashboard-client',"
echo "  '\$2a\$11\$hashed_secret_here', -- You need to hash 'dashboard-secret-123'"
echo "  'Administrative dashboard for managing services',"
echo "  true,"
echo "  '{\"http://localhost:5201\", \"https://admin.yourdomain.com\"}',"
echo "  '{\"admin:read\", \"admin:write\", \"users:manage\"}',"
echo "  NOW()"
echo ");"
echo ""
echo "-- Mobile App"
echo "INSERT INTO \"Applications\" (\"Id\", \"Name\", \"ClientId\", \"ClientSecret\", \"Description\", \"IsActive\", \"AllowedOrigins\", \"AllowedScopes\", \"CreatedAt\")"
echo "VALUES ("
echo "  gen_random_uuid(),"
echo "  'Mobile Application',"
echo "  'mobile-app-client',"
echo "  '\$2a\$11\$hashed_secret_here', -- You need to hash 'mobile-app-secret-123'"
echo "  'iOS and Android mobile applications',"
echo "  true,"
echo "  '{\"app://mobile\"}',"
echo "  '{\"profile:read\", \"profile:write\"}',"
echo "  NOW()"
echo ");"
echo ""
echo "✅ Copy and execute these SQL commands in your PostgreSQL database"
echo "   Database: aqlaanauth at 149.200.251.12:5432"
